port: 3000
db:
  user: root
  password: password
  host : 127.0.0.1
  database: todo
options:
  auth_token: open_says_me
  dateFormat: YYYY-MM-DD
  tracking_id: qubitproducts
  version: 1.0.0
  host: "http://localhost:3000"
log:
  sentry: false
  console:
    level: debug
